name: Update Site (External)

on:
  push:
    branches: [ master ]
    paths:
      - 'external.p2/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      working-directory: external.p2
      run: mvn -U -B p2:site --file pom.xml
   
    - name: Upload External.p2
      uses: actions/upload-artifact@v1.0.0
      with:
        name: external-updatesite
        path: external.p2/target/repository
    
    - name: Checkout gh-pages
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
        
    - name: Remove External.p2 folder
      run: rm -rf external
    
    - name: Download External.p2
      uses: actions/download-artifact@v4.1.7
      with:
        name: external-updatesite
        path: external
    
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f external
        git commit -m "Automated commit"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        tags: false
        github_token: ${{ secrets.GITHUB_TOKEN }}    